version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/pdf
      - mv $READTHEDOCS_OUTPUT/html/document.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: requirements.txt
